### ISSUE TITLE
Quantitative test coverage is not demonstrable

### ISSUE THREAD

**Issue by bartziengs** [lmikaellukerad/hicondext#20]
We should make use of coverage tools in either unity (which probably is not possible) or Visual Studio.

**Comment by arjanvanschendel** [comment]
There is no ready-to-go solution for code coverage in Unity. There are three possible workarounds:

- Edit the Unity.dll file. We tried doing this, but information we found online only showed how to do this in old(er) versions of Unity, these methods did not work in our version. We decided that figuring out how to do this would not be worth the amount of time it would cost.
- Seperate logic code from Unity code, and show the coverage of the logic code. Doing this at this stage of the project would cost insane amounts of time, and the amount of code that can actually be seperated is not that much.
- The last options is to manually go through all the code, and see what is tested. This is probably the easiest method, and we can also measure the coverage of unity code this way.
